# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Start Docker Container
      run: |
        docker run -d -p 7080:5000 gprestes/the-internet
      shell: bash
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Wait for the application to start (adjust sleep time)
      run: |
        sleep 10
      shell: bash
    - name: Test
      uses:  ./
      with:
        test-assembly-path: TestScenario/bin/Release/net6.0
        test-assembly-dll: TestScenario.dll
        output-html: TestScenario.html
        framework: net6.0
    - name: Copy Screenshots
      run: |
        mkdir -p screenshots  # Create a directory to store screenshots
        # Copy your screenshots from the original location to the screenshots directory
        # Example: cp /path/to/screenshots/*.png screenshots/
      shell: bash
  
    - name: Create Artifacts Archive
      run: |
        # Create a zip archive that includes the screenshots
        zip -r artifacts.zip screenshots
      shell: bash
    
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: 'Test Artifacts'
        path: artifacts.zip
        