# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Start Docker Container
      run: |
        docker run -d -p 7080:5000 gprestes/the-internet
      shell: bash
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      uses:  ./
      with:
        test-assembly-path: TestScenario/bin/Release/net6.0
        test-assembly-dll: TestScenario.dll
        test-execution-json: TestScenario/bin/Release/net6.0/TestExecution.json
        output-html: TestScenario.html
        framework: net6.0
